#!/usr/bin/env bash
set -euo pipefail

# Objective smoke test for the Save as PDF button in plan-agent HTML plans
# (docs/plans/port-pdf-export-button-to-plan-agent.html).
#
# The button originally shipped only in the markdown-to-html assets (PR #272,
# then in the standalone plan-interview plugin, now merged into plan-agent
# 4.0.0); plans generated by plan-agent's implementation-plan skeleton never
# had it. These asserts pin the ported feature to the skeleton and its
# SKILL.md contract so the two pipelines cannot silently diverge again.

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
SKELETON="$ROOT/kit/plugins/plan-agent/skills/implementation-plan/reference/SKELETON.html"
PLAN_SKILL="$ROOT/kit/plugins/plan-agent/skills/implementation-plan/SKILL.md"
FAILURES=0

echo "=== Save as PDF Button Smoke Test ==="

echo "1. SKELETON.html header has save-pdf-btn between the title and the status badge..."
if python3 - "$SKELETON" << 'PYEOF'
import re, sys
html = open(sys.argv[1]).read()
top = re.search(r'<div class="plan-header-top">(.*?)</div>', html, re.S)
sys.exit(0 if top and re.search(
    r'plan-title.*save-pdf-btn.*status-badge', top.group(1), re.S) else 1)
PYEOF
then
  echo "  PASS"
else
  echo "  FAIL: save-pdf-btn is not between .plan-title and .status-badge in .plan-header-top"
  FAILURES=$((FAILURES + 1))
fi

echo "2. Button wiring: type=button, onclick=savePDF(), aria-label present..."
if grep -q 'class="save-pdf-btn" type="button" onclick="savePDF()"' "$SKELETON" \
   && grep -q 'aria-label="Save this plan as PDF"' "$SKELETON"; then
  echo "  PASS"
else
  echo "  FAIL: button markup is missing type/onclick/aria-label wiring"
  FAILURES=$((FAILURES + 1))
fi

echo "3. savePDF() is defined in the inline script and calls window.print()..."
if awk '/function savePDF\(\)/{f=1} f{print} f && /\}/{exit}' "$SKELETON" \
     | grep -q 'window\.print()'; then
  echo "  PASS"
else
  echo "  FAIL: savePDF() missing or does not call window.print()"
  FAILURES=$((FAILURES + 1))
fi

echo "4. .save-pdf-btn is hidden in the @media print block..."
# The skeleton has several single-line @media print component rules plus the
# main multi-line block; the button hide must live inside one of them.
if grep -A 6 '@media print' "$SKELETON" \
     | grep 'display: none' | grep -q '\.save-pdf-btn'; then
  echo "  PASS"
else
  echo "  FAIL: @media print does not hide .save-pdf-btn"
  FAILURES=$((FAILURES + 1))
fi

echo "5. .save-pdf-btn CSS class is defined..."
if grep -q '^  \.save-pdf-btn {' "$SKELETON"; then
  echo "  PASS"
else
  echo "  FAIL: .save-pdf-btn CSS block not found in SKELETON.html"
  FAILURES=$((FAILURES + 1))
fi

echo "6. implementation-plan SKILL.md documents the Save as PDF button requirement..."
if grep -q 'Save as PDF button' "$PLAN_SKILL" && grep -q 'save-pdf-btn' "$PLAN_SKILL"; then
  echo "  PASS"
else
  echo "  FAIL: SKILL.md HTML Output Requirements does not document the button"
  FAILURES=$((FAILURES + 1))
fi

echo
if [ "$FAILURES" -eq 0 ]; then
  echo "All Save as PDF assertions passed."
else
  echo "$FAILURES assertion(s) failed."
  exit 1
fi
